# Generated by Django 6.0.3 on 2026-03-30 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost_price', models.FloatField(default=0)),
                ('selling_price', models.FloatField(default=0)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('commission_rate', models.FloatField(default=15.0, verbose_name='Pazar Yeri Komisyon Oranı (%)')),
                ('shipping_cost', models.FloatField(default=40.0, verbose_name='Kargo Ücreti (₺)')),
                ('monthly_revenue_goal', models.FloatField(default=100000.0, verbose_name='Aylık Ciro Hedefi (₺)')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası')),
                ('two_factor_auth', models.BooleanField(default=False, verbose_name='İki Adımlı Doğrulama')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='E-Posta Bildirimleri')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
