# Generated by Django 6.0.3 on 2026-04-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='monthly_revenue_goal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='two_factor_auth',
        ),
    ]
