# Generated by Django 6.0.3 on 2026-04-24 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_default_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date'], 'verbose_name': 'Satış', 'verbose_name_plural': 'Satışlar'},
        ),
        migrations.AlterField(
            model_name='product',
            name='commission_rate',
            field=models.FloatField(default=0.0, verbose_name='Pazar Yeri Komisyon Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Maliyet Fiyatı (₺)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Satış Fiyatı (₺)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_cost',
            field=models.FloatField(default=0.0, verbose_name='Kargo Ücreti (₺)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Stok Miktarı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(verbose_name='Satış Tarihi'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Satış Fiyatı (₺)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.FloatField(default=1.0, verbose_name='Adet'),
        ),
    ]
