# Generated by Django 6.0.3 on 2026-04-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_supportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
