# Generated by Django 6.0.3 on 2026-03-30 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_revenue_goal', models.FloatField(default=100000.0, verbose_name='Aylık Ciro Hedefi')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
