# Generated by Django 6.0.3 on 2026-04-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
