# Generated by Django 6.0.3 on 2026-04-24 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_shopier_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profiller'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='two_factor_auth',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='E-posta Bildirimleri'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='monthly_revenue_goal',
            field=models.FloatField(default=100000.0, verbose_name='Aylık Ciro Hedefi (₺)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shopier_webhook_secret',
            field=models.CharField(blank=True, help_text='Shopier Panel → Hesap Ayarları → Webhook Secret', max_length=255, null=True, verbose_name='Shopier Webhook Secret'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
