# Generated by Django 6.0.3 on 2026-04-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_options_remove_profile_two_factor_auth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shopier_webhook_secret',
        ),
        migrations.AlterField(
            model_name='profile',
            name='shopier_api_key',
            field=models.TextField(blank=True, help_text='Shopier API erişimi için kullanılan uzun erişim anahtarı.', null=True, verbose_name='Shopier API Anahtarı'),
        ),
    ]
