# Generated by Django 6.0.3 on 2026-04-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_shopier_webhook_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
    ]
