# Generated by Django 6.0.3 on 2026-04-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_auto_renew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auto_renew',
            field=models.BooleanField(default=True, verbose_name='Otomatik Yenileme'),
        ),
    ]
